<?php

use \MageMastery\Todo\Block\Template;

/** @var Template $block */

?>

<ul>
  <li>
    Task 1
  </li>
  <li>
    Task 2
  </li>
  <li>
    Task 3
  </li>
</ul>
<div data-bind="scope: 'todo'">
  <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
  {
    "*": {
      "Magento_Ui/js/core/app": {
        "components": {
          "todo": {
            "component": "MageMastery_Todo/js/view/todo",
            "template": "MageMastery_Todo/todo",
            "tasks": [
              {"label": "Task 4"},
              {"label": "Task 5"},
              {"label": "Task 6"}
            ]
          }
        }
      }
    }
  }
</script>